'''
print("14+7=21")
print("14*7=28")
print("14-7=7")
print("14/7=2")
'''
''' 
firstNumber=14
secondNumber=7
print("14+7=",firstNumber+secondNumber)
print("14*7=",firstNumber*secondNumber)
print("14-7=",firstNumber-secondNumber)
print("14/7=",firstNumber/secondNumber)
'''
firstNumber=28
secondNumber=7
print(firstNumber,"+",secondNumber,"=",firstNumber+secondNumber)
print(firstNumber,"*",secondNumber,"=",firstNumber*secondNumber)
